### ISSUE TITLE
为何使用RxJava？可以带来什么样的好处？

### ISSUE THREAD

**Issue by coding4m** [liulongbiao/fastdfs-client#1]
hi，@liulongbiao 如题，望可以解答下。

**Comment by liulongbiao** [comment]
Netty 是异步网络框架，每次操作返回 Promise 对象，然后监听该 Promise 对象的完成或失败来进一步处理；而监听模式下将多个异步操作组合到一起不是很方便。而 fastdfs 客户端每一次交互都会涉及两次异步交互，一次从 tracker 获取某个 storage 地址，然后再到 storage 上进行数据操作。使用 RxJava 可以很自然地将异步操作链到一起，如 FastdfsClient 实现中各命令的实现。

**Comment by coding4m** [comment]
@liulongbiao 似乎CompletableFuture更满足你的要求

**Comment by liulongbiao** [comment]
嗯，是的。使用JDK原生类可以减少额外的依赖。
这个项目开始的时候也只是为了学习，开始是学 Netty，后面是学 RxJava，在这过程中踩踩一些坑。
后面有空我也会学一下 CompletableFuture 的使用，谢谢你的建议
